# Generated by Django 2.0.6 on 2018-06-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='actor',
            new_name='genre',
        ),
        migrations.RemoveField(
            model_name='category',
            name='movie_poster',
        ),
        migrations.AddField(
            model_name='category',
            name='imdb',
            field=models.CharField(default=10, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_poster',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='year',
            field=models.CharField(max_length=6),
        ),
    ]
