# Generated by Django 2.0.6 on 2018-06-03 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20180603_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='imdb',
        ),
    ]
