# Generated by Django 2.0.6 on 2018-06-04 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_category_imdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='genre',
            new_name='actor',
        ),
        migrations.RemoveField(
            model_name='category',
            name='year',
        ),
    ]
